version: "3.9"
services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports: 
      - 2717:27017
    volumes:
      - mongo_db:/data/db

  # Node Api service
  api:
    build: .
    image: lekejosh/api
    restart: always
    volumes:
      - .:/usr/src/app
    ports:
      - "${PORT}:${PORT_1}"
    environment:
      JWT_EXPIRE: "${{ secrets.JWT_EXPIRE }}"
      JWT_SECRET: "${{ secrets.JWT_SECRET }}"
      PORT: "${{ secrets.PORT_1 }}"
      DB_URI: "${{ secrets.DB_URI }}"
      DB_NAME: reservation
      COOKIE_EXPIRE: "${{ secrets.COOKIE_EXPIRE }}"
      SMPT_SERVICE: "${{ secrets.SMPT_SERVICE }}"
      SMPT_HOST: "${{ secrets.SMPT_HOST }}"
      SMPT_PORT: "${{ secrets.SMPT_PORT }}"
      SMPT_MAIL: "${{ secrets.SMPT_MAIL }}"
      SMPT_PASSWORD: "${{ secrets.SMPT_PASSWORD }}"
      CLOUDINARY_NAME: "${{ secrets.CLOUDINARY_NAME }}"
      CLOUDINARY_APIKEY: "${{ secrets.CLOUDINARY_APIKEY }}"
      CLOUDINARY_SECRET: "${{ secrets.CLOUDINARY_SECRET }}"
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
