name: Docker Series Builds

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker login
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          .docker login -u $DOCKER_USERNAME -p DOCKER_PASSWORD
      - name: docker build mongodb
        run: |
          .docker build ./mongo_db -t  mongo:latest
      - name: docker build nodejs api
        run: |
          .docker build ./api -t  lekejosh/api
      - name: docker push
        run: |
          docker push mongo:latest
          docker push lekejosh/api
