name: Publish Docker image

on:
  push:
    branches:
      - master

jobs:
  build-images:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    env:
      JWT_EXPIRE: 4d
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      PORT: 4000
      PORT_1: 8080
      DB_URI: "mongodb://mongo_db:27017"
      DB_NAME: "reservation"
      COOKIE_EXPIRE: 5
      SMPT_SERVICE: gmail
      SMPT_HOST: smtp.gmail.com
      SMPT_PORT: 587
      SMPT_MAIL: oluwaronaldo7@gmail.com
      SMPT_PASSWORD: ${{ secrets.SMPT_PASSWORD }}
      CLOUDINARY_NAME: ddkil2k9c
      CLOUDINARY_APIKEY: 959645165615747
      CLOUDINARY_SECRET: ${{ secrets.CLOUDINARY_SECRET }}
    steps:
      # Log into GitHub container registry
      - name: Log into registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # Check out the repo
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Checkout
        uses: actions/checkout@v2
      # Build the images
      - name: Build the docker-compose stack
        run: docker-compose -f docker-compose.yml build
      # List images
      - name: List images
        run: docker images
      # Push images
      - name: Push images
        run: docker-compose -f docker-compose.yml push --ignore-push-failures
      # Log in to Docker Hub
      
      # Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: latest
